# author: Xerxes 2022-2-24

WEIFU_CAN_TRANSCEIVER_ROOT = $(WEIFU_ROOT)/can_transceiver

WEIFU_CAN_TRANSCEIVER_CSRCDIR = $(WEIFU_CAN_TRANSCEIVER_ROOT)
WEIFU_CAN_TRANSCEIVER_ASMSRCDIR = $(WEIFU_CAN_TRANSCEIVER_ROOT)

# find all the source files in the target directories
WEIFU_CAN_TRANSCEIVER_CSRCS = $(call get_csrcs, $(WEIFU_CAN_TRANSCEIVER_CSRCDIR))
WEIFU_CAN_TRANSCEIVER_ASMSRCS = $(call get_asmsrcs, $(WEIFU_CAN_TRANSCEIVER_ASMSRCDIR))

# get object files
WEIFU_CAN_TRANSCEIVER_COBJS = $(call get_relobjs, $(WEIFU_CAN_TRANSCEIVER_CSRCS))
WEIFU_CAN_TRANSCEIVER_ASMOBJS = $(call get_relobjs, $(WEIFU_CAN_TRANSCEIVER_ASMSRCS))
WEIFU_CAN_TRANSCEIVER_OBJS = $(WEIFU_CAN_TRANSCEIVER_COBJS) $(WEIFU_CAN_TRANSCEIVER_ASMOBJS)

# get dependency files
WEIFU_CAN_TRANSCEIVER_DEPS = $(call get_deps, $(WEIFU_CAN_TRANSCEIVER_OBJS))


# genearte library
WEIFU_CAN_TRANSCEIVER_LIB = $(OUT_DIR)/lib_weifu_can_transceiver.a

COMMON_COMPILE_PREREQUISITES += $(WEIFU_CAN_TRANSCEIVER_ROOT)/can_transceiver.mk

# library generation rule
$(WEIFU_CAN_TRANSCEIVER_LIB): $(WEIFU_CAN_TRANSCEIVER_OBJS)
	$(TRACE_ARCHIVE)
	$(Q)$(AR) $(AR_OPT) $@ $(WEIFU_CAN_TRANSCEIVER_OBJS)
	

WF_CAN_TRANSCEIVER_CFLAG ?= -Wno-unused-variable 
	
# specific compile rules
# user can add rules to compile this library
# if not rules specified to this library, it will use default compiling rules
.SECONDEXPANSION:
$(WEIFU_CAN_TRANSCEIVER_COBJS): $(OUT_DIR)/%.o : %.c $$(COMMON_COMPILE_PREREQUISITES)
	$(TRACE_COMPILE)
	$(Q)$(CC) -c $(COMPILE_OPT) $(COMPILE_HW_OPT) $(WF_CAN_TRANSCEIVER_CFLAG) $< -o $@
	

.SECONDEXPANSION:
$(WEIFU_CAN_TRANSCEIVER_ASMOBJS): $(OUT_DIR)/%.o : %.s $$(COMMON_COMPILE_PREREQUISITES)
	$(TRACE_COMPILE)
	$(Q)$(CC) -c $(ASM_OPT) $(COMPILE_HW_OPT) $< -o $@

CALTERAH_COMMON_CSRC += $(WEIFU_BASEBAND_CSRCS)
CALTERAH_COMMON_ASMSRCS += $(WEIFU_BASEBAND_ASMSRCS)

CALTERAH_COMMON_COBJS += $(WEIFU_CAN_TRANSCEIVER_COBJS)
CALTERAH_COMMON_ASMOBJS += $(WEIFU_CAN_TRANSCEIVER_ASMOBJS)

CALTERAH_COMMON_LIBS += $(WEIFU_CAN_TRANSCEIVER_LIB)
